CHECKPOINT_DIR = "_fastflow_experiment_checkpoints"

MVTEC_CATEGORIES = [
"paperclips_front",
"paperclips_side"
]

BACKBONE_DEIT = "deit_base_distilled_patch16_384"
BACKBONE_CAIT = "cait_m48_448"
BACKBONE_RESNET18 = "resnet18"
BACKBONE_WIDE_RESNET50 = "wide_resnet50_2"

SUPPORTED_BACKBONES = [
    BACKBONE_DEIT,
    BACKBONE_CAIT,
    BACKBONE_RESNET18,
    BACKBONE_WIDE_RESNET50,
]

BATCH_SIZE = 8
NUM_EPOCHS = 70
LR = 1e-3
WEIGHT_DECAY = 1e-5

LOG_INTERVAL = 37
EVAL_INTERVAL = 10
CHECKPOINT_INTERVAL = 50